name: Yarn audit improved
description: |
  Run yarn audit with ignore list
inputs:
  working-directory:
    description: The working directory to run the audit in
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check yarn version
      id: version_check
      run: |
        echo "classic_yarn=false" >> $GITHUB_ENV
        yarn_version=$(yarn --version)
        echo "Yarn version: $yarn_version"
        if [[ "$(printf '%s\n' "2.0.0" "$yarn_version" | sort -V | head -n1)" != "2.0.0" ]]; then
          echo "classic_yarn=true" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Run audit and always exit with code 0
      if: ${{env.classic_yarn == 'true'}}
      run: |
        echo "Classic yarn detected"
        if yarn audit --json > audit.json; then
          echo "Audit succeeded"
        fi
        python ${{ github.action_path }}/scripts/audit-resolver.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run audit and always exit with code 0
      if: ${{env.classic_yarn == 'false'}}
      run: |
        echo "Yarn 2 or greater detected"
        if yarn npm audit --json > audit.json; then
          echo "Audit succeeded"
        fi
        python ${{ github.action_path }}/scripts/audit-resolver-berry.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
