name: Scan web application for security vulnerabilities
description: |
  Scan application for security vulnerabilities with OWASP ZAP Full Scan
inputs:
  azure_user:
    description: Set Azure user
    required: true
    default: true
  azure_password:
    description: Set Azure password
    required: true
    default: null
  target:
    description: URL of the web application to be scanned
    required: true
  cmd_options:
    description: Set additional command line parameters
    required: false
  zap_login:
    description: Azure login script
    required: true
  zap_configfile:
    description: Config for zap to use. Include ajax spider and active scan
    required: false
  zap_rules:
    description: Rules for ZAP to ignore
    required: false
  report_artifact:
    description: Report artifact name
    default: vuln-full-scan-report
    required: false
runs:
  using: composite
  steps:
    - name: Scan with ZAP full scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: ${{ inputs.target }}
        rules_file: ${{ inputs.zap_rules }}
        cmd_options: | 
          -config script.scripts.name="http-sender.py" \
		      -config script.scripts.engine="Jython" \
		      -config script.scripts.type=http-sender \
          -config script.scripts.enabled=true \
          -config script.scripts.file=${{ inputs.zap_login }} \
          -configfile ${{ inputs.zap_configfile }} \
          '${{ inputs.cmd_options }}'
        allow_issue_writing: false
      env:
        ZAP_BASE_URL: ${{ inputs.target }}
        ZAP_MS_USER: ${{ inputs.azure_user }}
        ZAP_MS_PASSWD: ${{ inputs.azure_password }}
    
    - name: Upload full scan results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ inputs.report_artifact }}
        path: report.html