name: NPM audit improved
description: |
  Run NPM audit with ignore list
runs:
  using: composite
  steps:
    - name: NPM audit to file and run python script
      run: |
        npm i --package-lock-only
        /usr/bin/touch audit.json
        /usr/bin/chmod a+rw audit.json
        npm audit --dry-run --json > audit.json
        python ${{ github.action_path }}/audit-resolver.py
      shell: bash
      working-directory: ${{ github.action_path }}
    

