name: NPM audit improved
description: |
  Run NPM audit with ignore list
runs:
  using: composite
  steps:
    - name: Run audit and always exit with code 0
      run: |
        if npm audit --json > audit.json; then
          exit 0
        fi
      shell: bash
    - name: Run python script
      run: |
        python ${{ github.action_path }}/audit-resolver.py
      shell: bash
      working-directory: ${{ github.workspace }}
    

