name: NPM audit improved
description: |
  Run NPM audit with ignore list
runs:
  using: composite
  steps:
    - name: Run audit and always exit with code 0
      run: |
        /usr/bin/touch audit.json
        /usr/bin/chmod a+rw audit.json
        EXIT_CODE=$(npm audit --json > audit.json)
        if [ $EXIT_CODE -eq 1 ]; then
          exit 0
        else
          exit $EXIT_CODE
        fi
      shell: bash
    - name: Run python script
      run: |
        python ${{ github.action_path }}/audit-resolver.py
      shell: bash
      working-directory: ${{ github.workspace }}
    

