name: NPM audit improved
description: |
  Run NPM audit with ignore list
runs:
  using: composite
  steps:
    - name: Run audit and always exit with code 0
      run: |
        /usr/bin/touch audit.json
        /usr/bin/chmod a+rw audit.json
        npm audit --dry-run --json > audit.json
        exit 0
      shell: bash
    - name: Run python script
      run: |
        python ${{ github.action_path }}/audit-resolver.py
      shell: bash
      working-directory: ${{ github.workspace }}
    

