name: NPM audit improved
description: |
  Run NPM audit with ignore list
runs:
  using: composite
  steps:
    - name: NPM audit to file and run python script
      run: |
        echo 0
        /usr/bin/touch audit.json
        echo 1
        /usr/bin/chmod a+rw audit.json
        echo 2
        npm audit --dry-run --json
        echo 3
        cat audit.json
        echo 4
        python ${{ github.action_path }}/audit-resolver.py
      shell: bash
      working-directory: ${{ github.workspace }}
    

