name: NPM audit improved
description: |
  Run NPM audit with ignore list
runs:
  using: composite
  steps:
    - name: Run audit and always exit with code 0
      run: |
        /usr/bin/touch ${{ github.action_path}}/audit.json
        /usr/bin/chmod a+rw ${{ github.action_path}}/audit.json
        if npm audit --json > ${{ github.action_path}}/audit.json; then
          exit 0
        fi
      shell: bash
    - name: Run python script
      run: |
        python ${{ github.action_path }}/audit-resolver.py
      shell: bash
      working-directory: ${{ github.workspace }}
    

